apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    spec:
      serviceAccountName: ceph-csi-sa
      restartPolicy: Never
      containers:
        - name: cephfs-post-install-job
          image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - '/bin/sh'
          args:
            - "-c"
            - |
              cp /apps/storage_classes/sc-cephfs.yaml /tmp/sc-cephfs.yaml
              if ! grep -q provisioner-secret-name /tmp/sc-cephfs.yaml; then
                echo "Adding ceph secret parameters to cephfs storage class."
                sed -i '/parameters:/a \   csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret\n   csi.storage.k8s.io/provisioner-secret-namespace: default\n   csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret\n   csi.storage.k8s.io/controller-expand-secret-namespace: default\n   csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret\n   csi.storage.k8s.io/node-stage-secret-namespace: default' /tmp/sc-cephfs.yaml
              else
                echo "cephfs storage class contains provisioner-secret-name -- proceeding."
              fi
              kubectl apply -f /tmp/sc-cephfs.yaml
          volumeMounts:
            - name: cephfs-csi-sc-vol
              mountPath: /apps/storage_classes/sc-cephfs.yaml
              subPath: sc-cephfs.yaml

# The config maps are created via cloud-init and the image.
# This occurs on the storage node where all this information lives
# and is required to be in place prior to the manifest.
      volumes:
        - name: cephfs-csi-sc-vol
          configMap:
            name: cephfs-csi-sc
